### ISSUE TITLE
Label with status of difficulty

### ISSUE THREAD

**Issue by mikejavier** [LFeh/frontend-challenges#13]
It would be nice to put a label to indicate the degree of difficulty of the test or show it level (jr .. senior .. etc).

**Comment by mikejavier** [comment]
We can be based on the requirements described in vacancies.

**Comment by paulinhapenedo** [comment]
I think that part of the challenge is to solve it according to your skill level. There's no right answer or right way to do it. Maybe recruiters will be looking at your commits as you develop a solution to the problem, trying to understand your line of thought. And maybe that will have a greater impact on wether you get the job or not, more than solving the problem.

**Comment by LFeh** [comment]
@paulinhapenedo Exactly!
