### ISSUE TITLE
Desafio Celular Direto

### ISSUE THREAD

**Issue by viniciuslagedo** [LFeh/frontend-challenges#32]
Fala man, beleza ?

O desafio da Celular Direto que está na lista é bem antigo e vai ser excluído, na verdade a Celular Direto não existe mais, virou Wooza. Em breve te mando um PR com o link do novo. Só pra deixar esse alerta.

Abraços !
;)

**Comment by LFeh** [comment]
Maravilha! Se quiser abre um PR removendo :)

**Comment by LFeh** [comment]
@viniciuslagedo

**Comment by viniciuslagedo** [comment]
Fiz lá, tinha esquecido mesmo.
