### ISSUE TITLE
Possíveis melhorias para o projeto.

### ISSUE THREAD

**Issue by nazarepiedady** [LFeh/frontend-challenges#48]
O projeto está muito bom, mas apenas acho que não levou em consideração alguns aspectos da área, tipos os níveis de experiência do desenvolvidor em `Junior`, `Senior` e `Pleno`.

# Possíveis melhorias:
* Quebrar os projetos em categorias segundo o nível de experiência.
* Recomendar referências segundo o nível de experiência.
* Divulgar mais o projeto nos grupos de front-end oficiais ou não.

**Comment by LFeh** [comment]
Fala @nandomoreirame, tudo bem?

Primeiramente obrigado pelos elogios 😄 

Vamos as respostas:

- Quebrar os projetos em categorias segundo o nível de experiência.
- Recomendar referências segundo o nível de experiência.

É muito dificil fazer essa separação, até porque o nível de senioridade pode váriar muito de uma empresa pra outra. E sinceramente, nem curto dividir dessa maneira. 

Acho que muitos Júniors fariam testes de Senior com tranquilidade e muito Senior teria dificuldades em testes de Juniors, hehe.

Divulgar mais o projeto nos grupos de front-end oficiais ou não.

Opa, conta muito com ajuda, hahaha, já fiz muito isso, mas atualmente estou deixando ser mais organico da minha parte. Mas se puder divulgar e pedir pra outras pessoas divulgarem, seria bem legal.

**Comment by nandomoreirame** [comment]
oi @LFeh acho que vc quis dizer @nazarepiedady 😃

**Comment by LFeh** [comment]
Shit de autocomplete, hahahahaha
