### ISSUE TITLE
But, if people know the tests and others people answers, it wont change the output of the test?

### ISSUE THREAD

**Issue by felquis** [LFeh/frontend-challenges#9]
This repo is great, the purpose is great! But this is a common question I hear inside companies when we talk about "open sourcing" challenges, and I would appreciate some words on this theme.

**Comment by LFeh** [comment]
:stuck_out_tongue_winking_eye: :pray:

**Comment by nandomoreirame** [comment]
:+1:

**Comment by fmeyer** [comment]
A hiring process involves a lot more than just code assessment, but this I will only retain my comments regarding the code challenges.

I've been recruiting, hiring and managing developers for some time. Just to give you an overview, in the last four years I conducted at least 500 interviews and hired more than 30 engineers. 

In my experience the code challenge isn't the only variable used to evaluate the candidate, it works more like a filter to get in qualified candidates. 

On my hiring processes, I always inform that after the code challenge is submitted, there will be an onsite interview to extend the proposed solution. This second round is usually more immersive and involves pair programming sessions, whiteboard brainstorming or other tools that I can use to make the people comfortable explaining the solution and proposing extensions. You would be surprised by how this filter works even if the code challenge is public and is a simple TODO app.

In general, the day to day of a developer involves a lot of information gathering to deliver a proper and suitable solution; How many times we use other people's gems, libraries, and answers from StackOverflow? If she or he was able to copy the previous code, understand it, make it better and, also improving it later, Isn't this person a good developer anyways?

**Comment by LFeh** [comment]
Awesome points @fmeyer. I agree.

**Comment by kvnol** [comment]
That's it, @fmeyer. I agree, too.
